---
abstract: 'Check a Phone Number (North American Numbering Plan)!'
author:
  - 'John Karr <brainbuz@brainbuz.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-Validator-Phone-NANP
no_index:
  directory:
    - t
    - inc
requires:
  Number::Phone: 2
  Number::Phone::Country: 1.7
  Number::Phone::NANP: 1.3
  String::Validator::Common: 0.93
  Test::More: 0
version: 0.10
